### ISSUE TITLE
Plugin does not create #channel directory in data directory

### ISSUE THREAD

**Issue by bernysk** [waratte/supybot#2]
Plugin cannot create cobe.brain file because it does not create /#channel directory in bot's /data directory. You need to create /#channel directory manually.

**Comment by seitzbg** [comment]
I did this and mine still won't work :(

```
ERROR 2017-07-06T22:38:44 supybot Exception id: 0xf4687
ERROR 2017-07-06T22:38:55 supybot Uncaught exception in Cobe.__call__:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supybot/log.py", line 363, in m
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/irclib.py", line 136, in __call__
    method(irc, msg)
  File "/home/supybot/johnny5/plugins/Cobe/plugin.py", line 237, in doPrivmsg
    self._learn(irc, msg, channel, text, probability) # Now we can pass this to our learn function!
  File "/home/supybot/johnny5/plugins/Cobe/plugin.py", line 157, in _learn
    commands.getoutput('{0} {1}'.format(self._doCommand(channel), 'init'))
NameError: global name 'commands' is not defined
ERROR 2017-07-06T22:38:55 supybot Exception id: 0xf4687
```

**Comment by seitzbg** [comment]
Looks like it needs: 'import commands' for Python 2.x.  Has been removed in 3.x, should use subprocess.
